### ISSUE TITLE
Update infographic

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-grid#104]
[The infographic](https://raw.githubusercontent.com/Financial-Times/o-grid/2166a6a8cc46354b2105a2c5c8f2a0dd4763379e/img/grid-system.fw.png) is made out of date by v4.0.0.

It was made with software (Adobe Fireworks) that designers don't necessarily use anymore and is no longer supported by Adobe.

For reusability and maintainability it should be made using Sketch.

Here is a work in progress: https://www.dropbox.com/s/vmcikb1lrg3luib/grid-system.sketch?dl=0

**Comment by callumlocke** [comment]
@AlbertoElias should we remove the outdated one from the readme? If it has any wrong dimension info, it would be better to get rid of it until a new one is made

**Comment by callumlocke** [comment]
> kaelig was unassigned by callumlocke

i didn't do that!

**Comment by AlbertoElias** [comment]
Ok, I'll try to find someone to help us out here

**Comment by kaelig** [comment]
Actually I believe the infographic should be up to date (haven't checked the numbers in it but the image is few days fresher than this issue).

In any case it's easy to edit it and export it. Files are in https://github.com/Financial-Times/o-grid/tree/master/img

**Comment by AlbertoElias** [comment]
It seems to be up to date
