### ISSUE TITLE
Generating the grid fails after adding a layout with a specific gutter width

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-grid#113]
See http://sassmeister.com/gist/a1b649ba0587aede5365

This fails to compile:
```scss
@include oGridAddLayout(
    $layout-name: P,
    $layout-width: 600px
    // Uncommenting this line causes a compilation error
    // , $gutter-width: 24px
);
@include oGridGenerate;
```

Uncomment line 846, and this happens:
```
invalid operands for multiplication on line 603 at column 19
```

The layout is added properly (and the gutter is registered correctly), but somehow the generation fails.

**Comment by triblondon** [comment]
We'll take a look.  Hi @kaelig are you using o-grid at Salesforce?

**Comment by kaelig** [comment]
Nope, we are using something that breaks away from typical grids and leverages the full power of flexbox. Note: we support IE 11 and above, which makes this possible.
