### ISSUE TITLE
Update readme to say whether $until is inclusive

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-grid#123]
```scss
@include oGridRespondTo($from: M, $until: L) {
  // ...
}
```

is that for M and L? or just M?

**Comment by kaelig** [comment]
See https://github.com/sass-mq/sass-mq, especially this section of the documentation: https://github.com/sass-mq/sass-mq#responsive-mode-on-default

If it were inclusive, the parameter would be `$through`.
