### ISSUE TITLE
Dividing row width between unknown amount of children

### ISSUE THREAD

**Issue by jamesnicholls** [Financial-Times/o-grid#126]
It would be useful if I could equally distribute the width of a row between an unknown amount of child elements. So if row contained 2 elements, they'd have a width of 50%, if it contained 3, a width of 33% (i.e. all child elements behave as if they had a `flex-grow` of 1).

Sorry if this functionality already exists but I couldn't find it in the documentation.

**Comment by AlbertoElias** [comment]
You might not want a grid in that case. Maybe you can use o-grid for the gutters, to keep them consistent with other sites, but I believe a grid layout is a bit more structured.

**Comment by AlbertoElias** [comment]
You might not want a grid in that case. Maybe you can use o-grid for the gutters, to keep them consistent with other sites, but I believe a grid layout is a bit more structured.

**Comment by jamesnicholls** [comment]
Yeah, fair point. Thought it might fit well in `o-grid` as it deals with layout, is already using `flex`\`table` display and has responsive features baked in.

**Comment by onishiweb** [comment]
Hi James, was there any action from this or can we close the issue?

**Comment by jamesnicholls** [comment]
I think it is useful functionality to have but understand that it doesn't really fit into o-grid, so happy to close.
