### ISSUE TITLE
Support disabling 'nice to have' features

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-grid#131]
Pull and push state and human friendly classes add _a lot_ to the file size but are either just syntactic sugar or cover pretty uncommon cases. It'd be nice to be able to turn them off via a mechanism similar to silent mode:

```
$o-grid-output-human-friendly-classes: true !default;
$o-grid-output-pull-push-classes: true !default;
```

**Comment by wheresrhys** [comment]
https://github.com/Financial-Times/o-grid/pull/132

**Comment by wheresrhys** [comment]
As an addendum to this issue, the `hide` keyword is bundled in with the human-friendly classes, but unlike those, it is not just an alias to some number as `0` is not supported as a column width. I suggest either `0` should be supported or `hide` shoudl not be bundled in the human-friendly mixin

**Comment by gvonkoss** [comment]
Closing as it has been done https://github.com/Financial-Times/o-grid/pull/136, and is being replaced with more relevant: https://github.com/Financial-Times/o-grid/issues/157
