### ISSUE TITLE
`one-half` issue in iOS8

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/o-grid#147]
Replacing `one-half` with `6` in `data-o-grid-colspan` fixed our iOS 8 issue below:

Before
<img width="1088" alt="screen shot 2017-02-04 at 18 51 49" src="https://cloud.githubusercontent.com/assets/3425322/22620795/3a8059bc-eb0b-11e6-8d69-c37c1abfdcdb.png">

After
<img width="1118" alt="screen shot 2017-02-04 at 18 52 04" src="https://cloud.githubusercontent.com/assets/3425322/22620796/3fc5d28a-eb0b-11e6-845a-795f9c44d5f7.png">

Not quite sure if this may have been just a bad interaction with some of our form styles, but just in case

**Comment by gvonkoss** [comment]
Closing, as this has been solved.
