### ISSUE TITLE
Documentation could be improved for some mixins.

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-grid#181]
We have some documentation for o-grid mixins which is not very helpful to users of Origami.
>oGridRespondTo(from, until)
>Apply styles at a given layout size Wrapper for the Sass MQ mq() mixin

We don't explain what Wrapper is, or what Sass MQ mq() mixin is.

I imagine there are other pieces of documentation like this as well.

**Comment by notlee** [comment]
https://github.com/Financial-Times/o-grid/pull/182
