### ISSUE TITLE
Deprecate: snappy mode

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-grid#200]
## What
Deprecate Snappy mode as it is not used in any new products/websites.

### What prompted this request?

@luketudorgriffiths brought it up in [#origami-chat](https://financialtimes.slack.com/archives/CSW6B2VAN/p1582553379012400)

### Describe what the new feature would do and how it would be used

Add a `@deprecate` call to the snappy mode parts of the codebase to mention it will be removed in the next major version.

**Comment by notlee** [comment]
good call

**Comment by notlee** [comment]
Deprecation released in v5.1.0
