### ISSUE TITLE
published npm package does not depend on sass-mq?

### ISSUE THREAD

**Issue by chee** [Financial-Times/o-grid#224]
https://www.npmjs.com/package/@financial-times/o-grid

https://github.com/Financial-Times/o-grid/blob/7f27e45923fa8b1a3e441bc75002fec150e18b92/bower.json#L8

???

**Comment by JakeChampion** [comment]
I checked on npm and it looks like it does depend on sass-mq -- https://www.npmjs.com/package/@financial-times/o-grid

<img width="702" alt="image" src="https://user-images.githubusercontent.com/1569131/86006527-fec6bd00-ba0d-11ea-84c2-b405055a58f3.png">
