### ISSUE TITLE
Specify columns widths using absolute or percent units

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-grid#26]
So we have

```html
<div data-o-grid-sizing="5 S12 XL3">
```

Where `5`, `12` and `3` are specifying column widths. And by using these numbers we are specifying a width relative to a total amount of columns, let's say in our case it's `12`.

So `6` is 50% of a `12` column grid.

But what if we change the total number of columns to be `16`? Must we change all references from `6` to `8`.

Would it be better to use a number system that more directly expresses the width of the element as a percentage of it's parent's column width?

So the html above could become

1.
```html
<div data-o-grid-sizing="50 S100 XL25">
```
or 2.
```html
<div data-o-grid-sizing="0.5 S1 XL0.25">
```
or 3.
```html
<div data-o-grid-sizing="5 S10 XL2.5">
```
or something similar?

**Comment by kaelig** [comment]
Please find the documentation of the human friendly keywords here: https://github.com/Financial-Times/o-grid/tree/refactor-mqs#using-keywords
