### ISSUE TITLE
js utility for applying the grid's breakpoints to modules

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-grid#38]
Related to the decision on how modules do responsiveness https://github.com/Financial-Times/ft-origami/issues/68 I think o-grid now needs a js utility for products. Something like.

```js
grid.applyResponsiveClasses({
   el: '.o-gallery', // selector or HTML el
   rules: [{
        layout: 'XL',
        class: 'o-gallery-massive'
      },{
        layout: '>S<XL',
        class: 'o-gallery-medium'
      }]
})
```
Arguably (because there are a few ways you can measure viewport width, and most are unreliable across devices) we could also do with another module which has a more generic implementation for applying any media query.

thoughts? @triblondon @dansearle-ft @richard-still-ft

**Comment by kaelig** [comment]
As stated previously: `getCurrentLayout()` will return the… current layout. Closing this.

**Comment by kaelig** [comment]
@AlbertoElias can we pair to write a test for the utility?

**Comment by AlbertoElias** [comment]
Not sure it's worth adding all the bloat to test one function which is
making sure a Sass mixin works =/

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by kaelig** [comment]
What about cross browser compatibility tests? Could we automate them?

**Comment by AlbertoElias** [comment]
Once the smoke test thing is set up (I'm working on adding it to obt), we can look at adding them to o-grid. @spriggsha has worked on creating them for o-overlay

**Comment by kaelig** [comment]
Great, ping me and we can pair on it.
