### ISSUE TITLE
Demos should be viewable online

### ISSUE THREAD

**Issue by tomgp** [Financial-Times/o-grid#67]
http://registry.origami.ft.com/components/o-grid@0.3.0
The demos linked from the o-grid documentation do not work online.

There is a link suggesting that the module should be installed locally but this link doesn't refer to anything on the page.

It would be very helpful if these demos were viewable online -- if not then why mention them in the online docs? Failing that the documentation should provide a guide for viewing the demos locally.

**Comment by kaelig** [comment]
Thanks Tom, good catch.

To install grids locally, you'll want to use bower:

```
bower install o-grid --save
```

At the moment I encourage you to use the beta version of grids.
http://build.origami.ft.com/files/o-grid@3.0.0-beta.7/demos/default.html

```
bower install o-grid#^3.0.0 --save
```

You may also add a bookmark with this URL to have an overlay on top of the new grid:

```
javascript:(function(){var s=document.createElement("script");s.src="http://www.kaelig.fr/grid-displayer/bookmarklet.js";document.head.appendChild(s);})();
```

That's what it looks like:

![screen shot 2015-02-10 at 10 41 51](https://cloud.githubusercontent.com/assets/85783/6125746/732fe9c0-b111-11e4-88d2-5031493cfec0.png)

**Comment by kaelig** [comment]
Actually it looks like you landed on a really old version of o-grid (0.3.0) which don't build anymore.

In the newer version of o-grid I couldn't find where there was a mention of a link to any 0.3.0 docs. Can you close this issue if the new documentation solved your issue?

**Comment by kaelig** [comment]
Also, please find the documentation for the beta directly on GitHub (the registry should support beta versions soon): https://github.com/Financial-Times/o-grid/tree/3.0.0-beta.7

**Comment by kaelig** [comment]
Closing this since it was just an issue with an old version.
