### ISSUE TITLE
Add display:block to o-grid-row

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-grid#72]
I would do  PR, but I imagine there'd be places where display:block needs to be carefully unset.

The use case is for using `<a>` tags as rows so that in next we can turn entire cards into links

**Comment by kaelig** [comment]
Sounds sensible, can you test it in next and make a PR for it?

**Comment by kaelig** [comment]
@wheresrhys any news on adding display: block to `o-grid-row`? Have you tested it on Next?

**Comment by wheresrhys** [comment]
ended up not turning entire cards into links so untested, but still seems like a sensible idea. A non display:block row doesn't make much sese

**Comment by kaelig** [comment]
Aren't you afraid it would add a lot of `display: block` in the codebase and the module itself for a small subset of uses?

**Comment by kaelig** [comment]
Closing this as it hasn't come up recently. Please reopen if you see a use case that would justify adding `display: block` to grid rows.
