### ISSUE TITLE
JS getCurrentLayout() always returns an empty string

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-grid#92]
```js
var oGrid = require('o-grid');

window.addEventListener('resize', function () {
  console.log(oGrid.getCurrentLayout());
});
```

If I use the above code and resize the window, it just logs an empty string over and over.

**Comment by JakeChampion** [comment]
@callumlocke Are you including the css in the page?
Here's an example using the build service - http://jsbin.com/fugiwabebu/edit?html,js,console,output
If you remove the `link` tag from the html and resize the output window, the console will log empty strings.

**Comment by callumlocke** [comment]
I'm using the Sass mixins. I didn't expect that the JS would depend on CSS.
Could we add that to the readme?

**Comment by kaelig** [comment]
Advanced features and edge cases for Sass usage aren't always detailed in the docs. In that case, I'd look at:

https://github.com/Financial-Times/o-grid#adding-a-layout
and main.scss at line 50: https://github.com/Financial-Times/o-grid/blob/master/main.scss#L50

Does this help?

If not, feel free to file a PR detailing usage for your use case.

**Comment by callumlocke** [comment]
Added note in readme to mention this. (Intended to PR but accidentally committed it directly – please revert if not OK!)
